# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(688, 686)
        self.scrollArea_2 = QtWidgets.QScrollArea(Form)
        self.scrollArea_2.setGeometry(QtCore.QRect(60, 250, 581, 141))
        self.scrollArea_2.setMaximumSize(QtCore.QSize(581, 141))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 603, 118))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.coke_R = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.coke_R.setMinimumSize(QtCore.QSize(91, 80))
        self.coke_R.setMaximumSize(QtCore.QSize(91, 80))
        self.coke_R.setObjectName("coke_R")
        self.horizontalLayout_3.addWidget(self.coke_R)
        self.coke_L = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.coke_L.setMinimumSize(QtCore.QSize(91, 80))
        self.coke_L.setMaximumSize(QtCore.QSize(91, 80))
        self.coke_L.setStyleSheet("ALL\n"
"EXTR")
        self.coke_L.setObjectName("coke_L")
        self.horizontalLayout_3.addWidget(self.coke_L)
        self.soda_R = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.soda_R.setMinimumSize(QtCore.QSize(91, 80))
        self.soda_R.setMaximumSize(QtCore.QSize(91, 80))
        self.soda_R.setObjectName("soda_R")
        self.horizontalLayout_3.addWidget(self.soda_R)
        self.soda_L = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.soda_L.setMinimumSize(QtCore.QSize(91, 80))
        self.soda_L.setMaximumSize(QtCore.QSize(91, 80))
        self.soda_L.setObjectName("soda_L")
        self.horizontalLayout_3.addWidget(self.soda_L)
        self.grape = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.grape.setMinimumSize(QtCore.QSize(91, 80))
        self.grape.setMaximumSize(QtCore.QSize(91, 80))
        self.grape.setObjectName("grape")
        self.horizontalLayout_3.addWidget(self.grape)
        self.orange = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.orange.setMinimumSize(QtCore.QSize(91, 80))
        self.orange.setMaximumSize(QtCore.QSize(91, 80))
        self.orange.setStyleSheet("ALL\n"
"EXTR")
        self.orange.setObjectName("orange")
        self.horizontalLayout_3.addWidget(self.orange)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.scrollArea_3 = QtWidgets.QScrollArea(Form)
        self.scrollArea_3.setGeometry(QtCore.QRect(60, 410, 581, 141))
        self.scrollArea_3.setMaximumSize(QtCore.QSize(581, 141))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 603, 118))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.fries_R = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.fries_R.setMinimumSize(QtCore.QSize(91, 80))
        self.fries_R.setMaximumSize(QtCore.QSize(91, 80))
        self.fries_R.setObjectName("fries_R")
        self.horizontalLayout_4.addWidget(self.fries_R)
        self.fries_L = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.fries_L.setMinimumSize(QtCore.QSize(91, 80))
        self.fries_L.setMaximumSize(QtCore.QSize(91, 80))
        self.fries_L.setStyleSheet("ALL\n"
"EXTR")
        self.fries_L.setObjectName("fries_L")
        self.horizontalLayout_4.addWidget(self.fries_L)
        self.chicken = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.chicken.setMinimumSize(QtCore.QSize(91, 80))
        self.chicken.setMaximumSize(QtCore.QSize(91, 80))
        self.chicken.setObjectName("chicken")
        self.horizontalLayout_4.addWidget(self.chicken)
        self.chz_fries = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.chz_fries.setMinimumSize(QtCore.QSize(91, 80))
        self.chz_fries.setMaximumSize(QtCore.QSize(91, 80))
        self.chz_fries.setObjectName("chz_fries")
        self.horizontalLayout_4.addWidget(self.chz_fries)
        self.chzstick = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.chzstick.setMinimumSize(QtCore.QSize(91, 80))
        self.chzstick.setMaximumSize(QtCore.QSize(91, 80))
        self.chzstick.setStyleSheet("ALL\n"
"EXTR")
        self.chzstick.setObjectName("chzstick")
        self.horizontalLayout_4.addWidget(self.chzstick)
        self.szn_fries = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.szn_fries.setMinimumSize(QtCore.QSize(91, 80))
        self.szn_fries.setMaximumSize(QtCore.QSize(91, 80))
        self.szn_fries.setStyleSheet("ALL\n"
"EXTR")
        self.szn_fries.setObjectName("szn_fries")
        self.horizontalLayout_4.addWidget(self.szn_fries)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_4)
        self.add_next = QtWidgets.QPushButton(Form)
        self.add_next.setGeometry(QtCore.QRect(230, 560, 211, 81))
        self.add_next.setObjectName("add_next")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(60, 90, 581, 141))
        self.scrollArea.setMaximumSize(QtCore.QSize(581, 141))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 615, 118))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.add_X = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.add_X.setMinimumSize(QtCore.QSize(91, 80))
        self.add_X.setMaximumSize(QtCore.QSize(91, 80))
        self.add_X.setObjectName("add_X")
        self.horizontalLayout_5.addWidget(self.add_X)
        self.add_all = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.add_all.setMinimumSize(QtCore.QSize(91, 80))
        self.add_all.setMaximumSize(QtCore.QSize(91, 80))
        self.add_all.setStyleSheet("ALL\n"
"EXTR")
        self.add_all.setObjectName("add_all")
        self.horizontalLayout_5.addWidget(self.add_all)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.textEdit_6 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_5)
        self.textEdit_6.setMinimumSize(QtCore.QSize(92, 40))
        self.textEdit_6.setMaximumSize(QtCore.QSize(92, 40))
        self.textEdit_6.setStyleSheet("font: 63 14pt \"나눔바른고딕\";")
        self.textEdit_6.setObjectName("textEdit_6")
        self.gridLayout_6.addWidget(self.textEdit_6, 0, 0, 1, 2)
        self.bacon_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.bacon_2.setMinimumSize(QtCore.QSize(40, 40))
        self.bacon_2.setMaximumSize(QtCore.QSize(40, 40))
        self.bacon_2.setObjectName("bacon_2")
        self.gridLayout_6.addWidget(self.bacon_2, 1, 0, 1, 1)
        self.bacon_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.bacon_4.setMinimumSize(QtCore.QSize(40, 40))
        self.bacon_4.setMaximumSize(QtCore.QSize(40, 40))
        self.bacon_4.setObjectName("bacon_4")
        self.gridLayout_6.addWidget(self.bacon_4, 1, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_6)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.textEdit_4 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_5)
        self.textEdit_4.setMinimumSize(QtCore.QSize(92, 40))
        self.textEdit_4.setMaximumSize(QtCore.QSize(92, 40))
        self.textEdit_4.setStyleSheet("font: 63 14pt \"나눔바른고딕\";")
        self.textEdit_4.setObjectName("textEdit_4")
        self.gridLayout_4.addWidget(self.textEdit_4, 0, 0, 1, 2)
        self.chz_1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.chz_1.setMinimumSize(QtCore.QSize(40, 40))
        self.chz_1.setMaximumSize(QtCore.QSize(40, 40))
        self.chz_1.setObjectName("chz_1")
        self.gridLayout_4.addWidget(self.chz_1, 1, 0, 1, 1)
        self.chz_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.chz_2.setMinimumSize(QtCore.QSize(40, 40))
        self.chz_2.setMaximumSize(QtCore.QSize(40, 40))
        self.chz_2.setObjectName("chz_2")
        self.gridLayout_4.addWidget(self.chz_2, 1, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_4)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.W_chz_1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.W_chz_1.setMinimumSize(QtCore.QSize(40, 40))
        self.W_chz_1.setMaximumSize(QtCore.QSize(40, 40))
        self.W_chz_1.setObjectName("W_chz_1")
        self.gridLayout_7.addWidget(self.W_chz_1, 1, 0, 1, 1)
        self.W_chz_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.W_chz_2.setMinimumSize(QtCore.QSize(40, 40))
        self.W_chz_2.setMaximumSize(QtCore.QSize(40, 40))
        self.W_chz_2.setObjectName("W_chz_2")
        self.gridLayout_7.addWidget(self.W_chz_2, 1, 1, 1, 1)
        self.textEdit_7 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_5)
        self.textEdit_7.setMinimumSize(QtCore.QSize(92, 40))
        self.textEdit_7.setMaximumSize(QtCore.QSize(92, 40))
        self.textEdit_7.setStyleSheet("font: 63 10pt \"나눔바른고딕\";")
        self.textEdit_7.setObjectName("textEdit_7")
        self.gridLayout_7.addWidget(self.textEdit_7, 0, 0, 1, 2)
        self.horizontalLayout_5.addLayout(self.gridLayout_7)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.textEdit_8 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_5)
        self.textEdit_8.setMinimumSize(QtCore.QSize(92, 40))
        self.textEdit_8.setMaximumSize(QtCore.QSize(92, 40))
        self.textEdit_8.setStyleSheet("font: 63 12pt \"나눔바른고딕\";")
        self.textEdit_8.setObjectName("textEdit_8")
        self.gridLayout_8.addWidget(self.textEdit_8, 0, 0, 1, 2)
        self.jala_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.jala_2.setMinimumSize(QtCore.QSize(40, 40))
        self.jala_2.setMaximumSize(QtCore.QSize(40, 40))
        self.jala_2.setObjectName("jala_2")
        self.gridLayout_8.addWidget(self.jala_2, 1, 0, 1, 1)
        self.jala_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.jala_4.setMinimumSize(QtCore.QSize(40, 40))
        self.jala_4.setMaximumSize(QtCore.QSize(40, 40))
        self.jala_4.setObjectName("jala_4")
        self.gridLayout_8.addWidget(self.jala_4, 1, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_8)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_5)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.coke_R.setText(_translate("Form", "콜라\n"
"R"))
        self.coke_L.setText(_translate("Form", "콜라\n"
"L"))
        self.soda_R.setText(_translate("Form", "사이다\n"
"R"))
        self.soda_L.setText(_translate("Form", "사이다\n"
"L"))
        self.grape.setText(_translate("Form", "포도쥬스"))
        self.orange.setText(_translate("Form", "오렌지쥬스"))
        self.fries_R.setText(_translate("Form", "감자튀김\n"
"R"))
        self.fries_L.setText(_translate("Form", "감자튀김\n"
"L"))
        self.chicken.setText(_translate("Form", "치킨너겟"))
        self.chz_fries.setText(_translate("Form", "치즈프라이"))
        self.chzstick.setText(_translate("Form", "치즈스틱"))
        self.szn_fries.setText(_translate("Form", "양념감자"))
        self.add_next.setText(_translate("Form", "OK"))
        self.add_X.setText(_translate("Form", "X"))
        self.add_all.setText(_translate("Form", "ALL\n"
"EXTRA"))
        self.textEdit_6.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'나눔바른고딕\'; font-size:14pt; font-weight:56; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">베이컨</p></body></html>"))
        self.bacon_2.setText(_translate("Form", "2장"))
        self.bacon_4.setText(_translate("Form", "4장"))
        self.textEdit_4.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'나눔바른고딕\'; font-size:14pt; font-weight:56; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">치즈</p></body></html>"))
        self.chz_1.setText(_translate("Form", "1장"))
        self.chz_2.setText(_translate("Form", "2장"))
        self.W_chz_1.setText(_translate("Form", "1장"))
        self.W_chz_2.setText(_translate("Form", "2장"))
        self.textEdit_7.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'나눔바른고딕\'; font-size:10pt; font-weight:56; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">화이트치즈</p></body></html>"))
        self.textEdit_8.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'나눔바른고딕\'; font-size:12pt; font-weight:56; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">할라피뇨</p></body></html>"))
        self.jala_2.setText(_translate("Form", "2개"))
        self.jala_4.setText(_translate("Form", "4개"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

